# Generated by Django 4.1.6 on 2023-03-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='scid',
            field=models.CharField(default='', max_length=70),
        ),
    ]
