# Generated by Django 4.1.6 on 2023-03-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0003_subcategory_scid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='scid',
            new_name='cid',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='companyname',
            field=models.CharField(default='', max_length=70),
        ),
    ]
