# Generated by Django 4.1.6 on 2023-03-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_rename_scid_subcategory_cid_subcategory_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='', max_length=70)),
                ('sid', models.CharField(default='', max_length=70)),
                ('modedlyear', models.CharField(default='', max_length=70)),
                ('price', models.CharField(default='', max_length=70)),
                ('registrationno', models.CharField(default='', max_length=70)),
                ('ownername', models.CharField(default='', max_length=150)),
                ('mobileno', models.CharField(default='', max_length=70)),
                ('color', models.CharField(default='', max_length=70)),
                ('fueltype', models.CharField(default='', max_length=70)),
                ('noofseats', models.CharField(default='', max_length=70)),
                ('transmissiontype', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
