# Generated by Django 4.1.6 on 2023-03-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0005_vehiclecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleCategory',
            new_name='Vehicle',
        ),
    ]
