# Generated by Django 4.1.6 on 2023-03-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0006_rename_vehiclecategory_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='modedlyear',
            new_name='modelyear',
        ),
    ]
