# Generated by Django 4.1.6 on 2023-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0008_vehicle_insured'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(default='', max_length=70),
        ),
    ]
