# Generated by Django 4.1.6 on 2023-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0010_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=150)),
                ('segment', models.CharField(default='', max_length=150)),
                ('model_name', models.CharField(default='', max_length=150)),
                ('price', models.CharField(default='', max_length=70)),
                ('insured', models.CharField(default='', max_length=70)),
                ('color', models.CharField(default='', max_length=70)),
                ('fueltype', models.CharField(default='', max_length=70)),
                ('noofseats', models.CharField(default='', max_length=70)),
                ('transmissiontype', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
                ('usericon', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
